language: generic

services:
  - docker

jobs:
  include:
    - env: LINUX_IMAGE_DISTRO=ubuntu
    - env: LINUX_IMAGE_DISTRO=centos

script:
  - bash -ex docker/build_from_travis.sh $LINUX_IMAGE_DISTRO

